/* Angelfish(tm) asynchronous tracking code for websites. */
var o=!0,r=null,v=!1;Array.prototype.indexOf||(Array.prototype.indexOf=function(t,s){var m=this.length>>>0,d=Number(s)||0,d=0>d?Math.ceil(d):Math.floor(d);for(0>d&&(d+=m);d<m;d++)if(d in this&&this[d]===t)return d;return-1});var R="016";
(function(t,s,m,d,S){function J(a){if(!a||!a.url)return o;var b=escape(a.p?a.p:d.i),b=b+("="+i.visitorId+"."+i.visitStartTime),b=b+("."+q(k.source.replace(/\&/g,""))+"%26"+q(k.medium.replace(/\&/g,""))+"%26"+q(k.campaign.replace(/\&/g,""))+"%26"+q(k.keyword.replace(/\&/g,""))+"%26"+q(k.content.replace(/\&/g,"")));return a.url.indexOf("?")>0?a.url+"&"+b:a.url+"?"+b}function q(a){return encodeURIComponent(decodeURIComponent(a.toString()))}function B(a,b){if(a&&!(a.length===0||typeof b!=="function"))for(var c in a)if(a.hasOwnProperty(c)&&
b(c)===v)break}function C(a,b,c,n){var l=a+"="+D(d.e!="auto"?d.e:s.domain)+"."+b+";";if(c){if(c!=="session"){var p="";if(n){p=new Date;p.setTime(p.getTime()+n*(c==="min"?6E4:864E5));p=p.toUTCString()}l=l+("expires="+p+";")}}else l=l+"expires=Thu, 01-Jan-1970 00:00:01 GMT;";d.j&&(l=l+("path="+d.j+";"));d.e!="auto"&&(l=l+("domain="+d.e+";"));s.cookie=l;u[a]=b}function y(){return Math.ceil((new Date).getTime()/1E3)}function E(){var a=(k.keyword||"").replace(/\&/g,""),a=k.ie?a:q(a),a=i.visitorId+"&"+
i.visitStartTime+"&"+i.lastActivityTime+"&"+q((k.source||"").replace(/\&/g,""))+"&"+q((k.medium||"").replace(/\&/g,""))+"&"+q((k.campaign||"").replace(/\&/g,""))+"&"+a+"&"+q((k.content||"").replace(/\&/g,""));C(d.d.sessionInfo,a,"day",d.w);u[d.d.sessionTimeout]||K()}function K(){C(d.d.sessionTimeout,i.visitorId,"session")}function T(){if(!w[d.i])return v;var a,b,c,n;a=w[d.i];b=a.indexOf(".");if(b>0)c=a.substring(0,b);else return v;n=a.indexOf(".",b+1);if(n>0)b=a.substring(b+1,n);else return v;a=a.substr(n+
1);a=a.split("&");if(a.length!=5)return v;i.visitorId=c;i.visitStartTime=b;i.visitId=q(i.visitorId+(parseInt(i.visitStartTime,10)?parseInt(i.visitStartTime,10):y()).toString());k.source=unescape(a[0]);k.medium=unescape(a[1]);k.campaign=unescape(a[2]);k.keyword=unescape(a[3]);k.content=unescape(a[4]);return o}function L(){if(!T()){var a;if(u[d.d.sessionInfo]){a=u[d.d.sessionInfo].split("&");i.visitorId=a[0];i.visitorType="returning";i.visitStartTime=parseInt(a[1],10);i.visitId=q(i.visitorId+(i.visitStartTime?
i.visitStartTime:y()).toString());i.lastActivityTime=a[2];k.source=a[3];k.medium=a[4];k.campaign=a[5];k.keyword=a[6];k.content=a[7];if(u[d.d.userDefined]){a=u[d.d.userDefined].split("&");a[0]==i.visitId&&(i.userDefined=a[1])}else i.userDefined=r;a=o}else{i.visitorType="new";a=v}a?parseInt(i.lastActivityTime,10)+d.s*60<y()?z():u[d.d.sessionTimeout]||z():z()}i.lastActivityTime=y();E()}function z(){if(!i.visitorId){var a=0,b;for(b=0;b<x.hostname.length;b++)a=a+x.hostname.charCodeAt(b);i.visitorId=q((a+
Math.floor(Math.random()*1E8)).toString());K()}i.visitStartTime=y();i.lastActivityTime=i.visitStartTime;i.visitId=q(i.visitorId+(i.visitStartTime?i.visitStartTime:y()).toString());i.pageviewCount=0;if(d.u!==1||!k.source)k=U()}function V(a){if(!a)return{hostname:"",queryParams:[],stem:""};var b,c,n,d="",p=[];b=a.indexOf("://");if(b===-1)return{r:v};b=b+3;c=a.indexOf("/",b);if(c===-1){c=a.indexOf("?",b);if(c===-1)n=a.substring(b);else{n=a.substring(b,c);p=a.substring(c+1).split("&")}}else{n=a.substring(b,
c);b=c+1;c=a.indexOf("?",b);if(c>-1){d=a.substring(b,c);p=a.substr(c+1).split("&")}else d=a.substr(b)}if((b=n.indexOf(":"))>-1)n=n.substring(0,b);return{hostname:n,queryParams:p,stem:"/"+d}}function M(a){var b,c="",n=v,l,p,k,j,i;if(!a)return{r:v};var m=V(a);p=m.hostname;k=m.queryParams;c=p;p=p.split(".");if(p.length===0)return{r:v};for(a=0;a<p.length-1;a++){l=p[a];if(d.f[l]){c=a+1<p.length?l+"."+p[a+1]:l;n=o;j=F[l.toLowerCase()]?l.toLowerCase():v;i=v;B(k,function(a){a=k[a].split("=");if(j&&a[0]===
F[j].B){i=a[1].toLowerCase();if(b)return v}if(a[0]===d.f[l]){c=l;b=a[1];if(!j||i)return v}return o});j&&!i&&(i=F[j]["default"]);if(b&&(!j||i=="utf8"||i=="utf-8")){b=decodeURIComponent(b);i=j=v}}}if(n&&b!=r){n={r:n,kw:b,hn:c};if(i)n.h=i;return n}return{r:n,hn:m.hostname}}function U(){var a={},b=s.referrer.replace(/\+/g,"%20"),c,n,l={};for(c in d.g)if(d.g.hasOwnProperty(c)!=v){l[c]=r;for(n in d.g[c])if(d.g[c].hasOwnProperty(n)!=v){a=d.g[c][n];if(w[a]){l[c]=w[a];break}}}if(l.source&&l.medium&&l.campaign){a=
{source:l.source,medium:l.medium,campaign:l.campaign,keyword:"",content:l.content||""};if(l.keyword)a.keyword=l.keyword;else{b=M(b);b.r&&typeof b.kw==="string"&&(a.keyword=b.kw)}}else{if(d.sourceOverwrite===0&&k.source&&k.medium)return k;b=M(b);if(b.hn&&b.hn==t.location.hostname)return k;if(b.r&&b.hn==="google"&&typeof w.gclid==="string")a={source:"google",medium:"cpc",campaign:"adwords",keyword:b.kw,content:""};else if(b.r)if(typeof b.kw==="string"){a={source:b.hn,medium:"organic",campaign:"(organic)",
keyword:b.kw||"(not provided)",content:""};if(b.h)a.h=b.h}else a={source:b.hn,medium:"referral",campaign:"(referral)",keyword:"",content:""};else a=b.hn?{source:b.hn,medium:"referral",campaign:"(referral)",keyword:"",content:""}:{source:"direct",medium:"(none)",campaign:"",keyword:"",content:""}}a.h||(a.keyword=a.keyword.toLowerCase());return a}function N(){if(!G){for(G=o;A.length;){var a,b;a=A.shift();if(a.method){b=a.method;delete a.method;b(a)}}setTimeout(N,500);G=v}}function W(a){var b,c,n;b=
a.page||x.pathname;n=b.indexOf(d.m);n>0&&(b=b.substr(0,n));(c=d.m)||(c="?");n=c=="?"?"#":"?";var l=a.page||x.href;c=l.lastIndexOf(c);if(c>0){l=l.substr(c+1);l=l.split(n);n=l[0]}else n="";b={t:"pv",pv:b,tt:a.title||s.title,qr:n};b.vt=i.visitorType;b.sc=k.source;b.md=k.medium;b.cp=k.campaign;b.kw=k.keyword;b.cn=k.content;k.ie&&(b.ie=k.ie);n=b;m&&(n.je=m.javaEnabled()?1:0);if(t&&t.screen){n.dp=t.screen.colorDepth;n.sh=t.screen.height;n.sw=t.screen.width}l=n=r;if(m&&m.userAgent)for(var p=[{source:m.userAgent,
a:/Version\/[.0-9]+ Mobile(\/[.A-Za-z0-9]+)? Safari/,c:"Version",b:"Mobile Safari"},{source:m.userAgent,a:/IEMobile\/[.0-9]+/,c:"IEMobile",b:"Internet Explorer Mobile"},{source:m.userAgent,a:/Chrome\/[.0-9]+ Mobile Safari\//,c:"Chrome",b:"Chrome Mobile"},{source:m.userAgent,a:/CriOS\/[.0-9]+ Mobile/,c:"CriOS",b:"Chrome Mobile"},{source:m.userAgent,a:/Opera Mobi\//,c:"Version",b:"Opera Mobile"},{source:m.userAgent,a:/Opera Mini\//,c:"Version",b:"Opera Mini"},{source:m.userAgent,a:/Mobile; rv:[.0-9]+\) Gecko\/[.0-9]+ Firefox\/[.0-9]+/,
c:"Firefox",b:"Mobile Firefox"},{source:m.userAgent,a:/Chrome\/[.0-9]+ Safari\//,c:"Chrome",b:"Chrome"},{source:m.userAgent,a:/rekonq\/[.0-9]+ Safari\//,c:"rekonq",b:"Rekonq"},{source:m.userAgent,a:/OmniWeb/,c:"OmniWeb/",b:"OmniWeb"},{source:m.userAgent,a:/Version\/[.0-9]+ Safari\//,c:"Version",b:"Safari"},{source:m.userAgent,a:/Opera\/[.0-9]+/,c:"Version",b:"Opera"},{source:m.userAgent,a:/iCab\/[.0-9]+/,c:"iCab",b:"iCab"},{source:m.userAgent,a:/Konqueror\/[.0-9]+/,c:"Konqueror",b:"Konqueror"},{source:m.userAgent,
a:/Firefox\/[.0-9]+/,c:"Firefox",b:"Firefox"},{source:m.userAgent,a:/Camino\/[.0-9]+/,c:"Camino",b:"Camino"},{source:m.userAgent,a:/Netscape\/[.0-9]+/,c:"Netscape",b:"Netscape"},{source:m.userAgent,a:/MSIE/,c:"MSIE",b:"Internet Explorer"},{source:m.userAgent,a:/Trident\/[.0-9]+/,c:"rv",b:"Internet Explorer"},{source:m.userAgent,a:/Gecko\/[.0-9]+/,c:"rv",b:"Mozilla"}],q=0;q<p.length;q++){var j=p[q].source;c=p[q].c;if(j&&j.match(p[q].a))n=p[q].b;if(n){p=m.userAgent.indexOf(c);if(p==-1){p=m.appVersion.indexOf(c);
p!=-1&&(l=parseFloat(m.appVersion.substring(p+c.length+1)))}else l=parseFloat(m.userAgent.substring(p+c.length+1));break}}c=X();b.bn=n;b.bv=l;b.pn=c.name;if(c.version)b.pr=c.version;b.bl=m.language?m.language.toLowerCase():m.userLanguage?m.userLanguage.toLowerCase():"";b.js=H;b.hn=x.hostname||"(not set)";b=O(b);P(b);if(typeof a.callback=="function"){n=a.callback;delete a.callback;a.hit=b;n(a)}i.pageviewCount===0&&i.userDefined&&Q({udv:i.userDefined});i.pageviewCount++}function Q(a){var b;i.userDefined=
a.udv;b=i.visitId+"&"+q(i.userDefined.replace(/\&/g,""));C(d.d.userDefined,b,"day",180);b={t:"udv",uv:i.userDefined};b=O(b);P(b);if(typeof a.callback=="function"){var c=a.callback;delete a.callback;a.hit=b;c(a)}}function O(a){var b,c=[];b=d.l==="auto"?x.protocol+"//":d.l?"https://":"http://";b=b+(d.n=="auto"?t.location.host:d.n);b=b+d.o;a.vi=i.visitorId;a.vs=i.visitId;a._=Math.floor(Math.random()*1E6);a.v=R;B(d.k,function(a){a=d.k[a];u[a]&&c.push(q(a+"="+u[a]))});a.ck=c.join(";");c=r;b=b+("?"+Y(a));
b.replace(/%20/g,"+");return b}function Y(a){var b=[];B(a,function(c){a[c]&&(c=="ie"||c=="kw"&&a.h?b.push(c+"="+a[c]):b.push(q(c)+"="+q(a[c])))});return b.join("&")}function P(a){if(I)(new Image).src=a.replace(/%20/g,"+")}function X(){if(!m||!m.userAgent)return{name:r,version:r};var a=m.userAgent,b=m.platform,c;if((c=a.match(/Windows\sNT\s(\d+\.\d+)/i))&&c.length>0){a=parseFloat(c[1]);return a===5?{name:"Windows",version:2E3}:a===5.1?{name:"Windows",version:"XP"}:a===5.2?{name:"Windows",version:"XP Professional"}:
a===6?{name:"Windows",version:"Vista"}:a===6.1?{name:"Windows",version:7}:a===6.2?{name:"Windows",version:8}:a===6.3?{name:"Windows",version:8.1}:{name:"Windows",version:a||"(not set)"}}if((c=a.match(/(iPod|iPad|iPhone).*?OS\s([0-9\_]+)/i))&&c.length>0)return{name:c[1],version:c[2].replace(/_/g,".")};if(a.indexOf("PSP (PlayStation Portable)")>-1)return{name:"PSP"};if(a.indexOf("PLAYSTATION 3")>-1)return{name:"Playstation 3"};if(a.toLowerCase().indexOf("xbox")>-1)return{name:"XBox"};if(a.toLowerCase().indexOf("googletv")>
-1)return{name:"Google TV"};if((c=a.match(/Android\s(\d+\.\d+)/i))&&c.length>0){a=parseFloat(c[1]);return{name:"Android",version:a}}if((c=a.match(/BlackBerry(\d+)\//i))&&c.length>0){a=parseFloat(c[1]);return{name:"BlackBerry",version:a}}if((c=a.match(/CrOS\s\S+\s([0-9.]+)/i))&&c.length>0)return{name:"Chrome OS",version:c[1]};if((c=b.match(/Linux\s(.+)/i))&&c.length>0)return{name:"Linux",version:c[1]};return(c=a.match(/Mac OS\s?X ((\d\.?)+)/i))&&c.length>0?{name:"Mac OS X",version:c[1]}:{name:b}}function D(a){function b(a,
b){var c,d,e,f,g;e=a&2147483648;f=b&2147483648;c=a&1073741824;d=b&1073741824;g=(a&1073741823)+(b&1073741823);return c&d?g^2147483648^e^f:c|d?g&1073741824?g^3221225472^e^f:g^1073741824^e^f:g^e^f}function c(a,c,d,g,e,f,h){a=b(a,b(b(c&d|~c&g,e),h));return b(a<<f|a>>>32-f,c)}function d(a,c,f,g,e,h,j){a=b(a,b(b(c&g|f&~g,e),j));return b(a<<h|a>>>32-h,c)}function l(a,c,d,g,f,e,h){a=b(a,b(b(c^d^g,f),h));return b(a<<e|a>>>32-e,c)}function i(a,c,d,g,e,f,h){a=b(a,b(b(d^(c|~g),e),h));return b(a<<f|a>>>32-f,c)}
function k(a){var b="",c="",d;for(d=0;d<=3;d++){c=a>>>d*8&255;c="0"+c.toString(16);b=b+c.substr(c.length-2,2)}return b}var j=[],m,q,s,t,e,f,g,h,a=function(a){for(var a=a.replace(/\r\n/g,"\n"),b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);if(d<128)b=b+String.fromCharCode(d);else{if(d>127&&d<2048)b=b+String.fromCharCode(d>>6|192);else{b=b+String.fromCharCode(d>>12|224);b=b+String.fromCharCode(d>>6&63|128)}b=b+String.fromCharCode(d&63|128)}}return b}(a),j=function(a){var b,c=a.length;b=c+8;for(var d=
((b-b%64)/64+1)*16,f=Array(d-1),g=0,e=0;e<c;){b=(e-e%4)/4;g=e%4*8;f[b]=f[b]|a.charCodeAt(e)<<g;e++}b=(e-e%4)/4;f[b]=f[b]|128<<e%4*8;f[d-2]=c<<3;f[d-1]=c>>>29;return f}(a);e=1732584193;f=4023233417;g=2562383102;h=271733878;for(a=0;a<j.length;a=a+16){m=e;q=f;s=g;t=h;e=c(e,f,g,h,j[a+0],7,3614090360);h=c(h,e,f,g,j[a+1],12,3905402710);g=c(g,h,e,f,j[a+2],17,606105819);f=c(f,g,h,e,j[a+3],22,3250441966);e=c(e,f,g,h,j[a+4],7,4118548399);h=c(h,e,f,g,j[a+5],12,1200080426);g=c(g,h,e,f,j[a+6],17,2821735955);f=
c(f,g,h,e,j[a+7],22,4249261313);e=c(e,f,g,h,j[a+8],7,1770035416);h=c(h,e,f,g,j[a+9],12,2336552879);g=c(g,h,e,f,j[a+10],17,4294925233);f=c(f,g,h,e,j[a+11],22,2304563134);e=c(e,f,g,h,j[a+12],7,1804603682);h=c(h,e,f,g,j[a+13],12,4254626195);g=c(g,h,e,f,j[a+14],17,2792965006);f=c(f,g,h,e,j[a+15],22,1236535329);e=d(e,f,g,h,j[a+1],5,4129170786);h=d(h,e,f,g,j[a+6],9,3225465664);g=d(g,h,e,f,j[a+11],14,643717713);f=d(f,g,h,e,j[a+0],20,3921069994);e=d(e,f,g,h,j[a+5],5,3593408605);h=d(h,e,f,g,j[a+10],9,38016083);
g=d(g,h,e,f,j[a+15],14,3634488961);f=d(f,g,h,e,j[a+4],20,3889429448);e=d(e,f,g,h,j[a+9],5,568446438);h=d(h,e,f,g,j[a+14],9,3275163606);g=d(g,h,e,f,j[a+3],14,4107603335);f=d(f,g,h,e,j[a+8],20,1163531501);e=d(e,f,g,h,j[a+13],5,2850285829);h=d(h,e,f,g,j[a+2],9,4243563512);g=d(g,h,e,f,j[a+7],14,1735328473);f=d(f,g,h,e,j[a+12],20,2368359562);e=l(e,f,g,h,j[a+5],4,4294588738);h=l(h,e,f,g,j[a+8],11,2272392833);g=l(g,h,e,f,j[a+11],16,1839030562);f=l(f,g,h,e,j[a+14],23,4259657740);e=l(e,f,g,h,j[a+1],4,2763975236);
h=l(h,e,f,g,j[a+4],11,1272893353);g=l(g,h,e,f,j[a+7],16,4139469664);f=l(f,g,h,e,j[a+10],23,3200236656);e=l(e,f,g,h,j[a+13],4,681279174);h=l(h,e,f,g,j[a+0],11,3936430074);g=l(g,h,e,f,j[a+3],16,3572445317);f=l(f,g,h,e,j[a+6],23,76029189);e=l(e,f,g,h,j[a+9],4,3654602809);h=l(h,e,f,g,j[a+12],11,3873151461);g=l(g,h,e,f,j[a+15],16,530742520);f=l(f,g,h,e,j[a+2],23,3299628645);e=i(e,f,g,h,j[a+0],6,4096336452);h=i(h,e,f,g,j[a+7],10,1126891415);g=i(g,h,e,f,j[a+14],15,2878612391);f=i(f,g,h,e,j[a+5],21,4237533241);
e=i(e,f,g,h,j[a+12],6,1700485571);h=i(h,e,f,g,j[a+3],10,2399980690);g=i(g,h,e,f,j[a+10],15,4293915773);f=i(f,g,h,e,j[a+1],21,2240044497);e=i(e,f,g,h,j[a+8],6,1873313359);h=i(h,e,f,g,j[a+15],10,4264355552);g=i(g,h,e,f,j[a+6],15,2734768916);f=i(f,g,h,e,j[a+13],21,1309151649);e=i(e,f,g,h,j[a+4],6,4149444226);h=i(h,e,f,g,j[a+11],10,3174756917);g=i(g,h,e,f,j[a+2],15,718787259);f=i(f,g,h,e,j[a+9],21,3951481745);e=b(e,m);f=b(f,q);g=b(g,s);h=b(h,t)}return(k(e)+k(f)+k(g)+k(h)).toLowerCase()}String.prototype.trim=
function(){return this.replace(/^[\s\xA0]+/,"").replace(/[\s\xA0]+$/,"")};var I=o,A=[],G=v,i={},k={},u={},w={agfoff:0,agf_off:0,gclid:r},x=s.location,H=1,F={baidu:{"default":"gb2312",parameter:"ie"},google:{"default":"utf-8",parameter:"ie"}};t[S]={enable:function(){return I=o},disable:function(){I=v;return o},setTrackingFile:function(a){if(!a)return v;d.o=a;return o},setTrackingHost:function(a){if(!a)return v;d.n=a;return o},setCookiePath:function(a){if(!a)return v;d.j=a;return o},setCookieDomain:function(a){if(!a)return v;
d.e=a;var b,c,i=RegExp(D(d.e!="auto"?d.e:s.domain)+"\\.");b=s.cookie.split(";");for(a=0;a<b.length;a++){c=b[a].split("=");if(c.length==2&&c[1].match(i)){c[1]=c[1].replace(i,"");var l=u,k=c[0].trim();c=c[1].trim();l[k]=decodeURIComponent(c)}}L();return o},setQueryDelimiter:function(a){if(!a||a!="?"&&a!="#")return v;d.m=a;return o},putCookiesInQuery:function(a){if(typeof a!="object"||!a.length)return v;d.k=a;return o},setHttps:function(a){if(typeof a!="boolean"&&a!="auto")return v;d.l=a;return o},addOrganicReferrer:function(a,
b){if(!a||!b)return v;d.f[a]=b;return o},removeOrganicReferrer:function(a){if(!a||!d.f[a])return v;delete d.f[a];return o},addQueryExclude:function(a){if(!a)return v;d.q.push(a);return o},pageview:function(a){typeof a!="object"&&(a={});a.method=W;A.push(a);return o},setUserDefined:function(a){if(typeof a!="object"||!a.udv)return v;a.method=Q;A.push(a);return o},getVisitInfo:function(){return i?i:{}},getMarketingVariables:function(){return k?k:{}},saveMarketingVariables:function(a){a.source&&(k.source=
a.source);a.medium&&(k.medium=a.medium);a.campaign&&(k.campaign=a.campaign);a.keyword&&(k.keyword=a.keyword);a.content&&(k.content=a.content);k.source||(k.source="");k.medium||(k.medium="");k.campaign||(k.campaign="");k.keyword||(k.keyword="");k.content||(k.content="");E();return o},resetVisit:function(){z();E();return o},setTransferQuery:function(a){if(a){d.i=a;return o}return v},getTransferUrl:J,transferVisitor:function(a){if(!a||!a.url)return o;t.location=J(a);return v},setJSVersion:function(a){if(a&&
!isNaN(a)&&a>H){H=parseFloat(a);return o}return v}};if(function(){var a=x.search.substring(1).split("&"),b,c,i=RegExp(D(d.e!="auto"?d.e:s.domain)+"\\."),l=[d.d.sessionInfo,d.d.sessionTimeout,d.d.userDefined];c=d.f.split(",");d.f={};for(b=0;b<c.length;b++){var k=c[b].split(":");d.f[k[0].trim()]=k[1].trim()}for(b=0;b<a.length;b++){c=a[b].split("=");w[c[0]]=decodeURIComponent(c[1])}if(w.A||w.z)return v;a=s.cookie.split(";");for(b=0;b<a.length;b++){c=a[b].split("=");if(c.length==2&&(l.indexOf(c[0].trim())==
-1||c[1].match(i))){c[1]=l.indexOf(c[0].trim())==-1?c[1]:c[1].replace(i,"");var k=u,m=c[0].trim();c=c[1].trim();k[m]=decodeURIComponent(c)}}b=[1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9];for(i=0;i<b.length;i++)s.write(unescape('%3Cscript language="Javascript'+b[i]+'"%3Eagf.setJSVersion('+b[i]+");%3C/script%3E"));return o}()){L();N()}})(window,document,navigator,{o:"/agf.gif",n:"auto",m:"?",k:[],l:"auto",f:"google:q,yahoo:p,msn:q,aol:q,lycos:query,ask:q,altavista:q,bing:q,netscape:query,cnn:query,looksmart:qt,about:terms,mamma:query,alltheweb:q,gigablast:q,voila:rdata,virgilio:qs,live:q,baidu:wd,alice:qs,yandex:text,najdi:q,club-internet:q,mama:query,seznam:q,search:q,wp:szukaj,onet:qt,netsprint:q,google.interia:q,szukacz:q,yam:k,pchome:q,duckduckgo:q",
q:[],g:{source:["agfs"],medium:["agfm"],campaign:["agfc"],keyword:["agfk"],content:["agfr"]},u:0,d:{sessionInfo:"agfs",sessionTimeout:"agft",userDefined:"agfudv"},j:"/",e:"auto",s:30,w:180,i:"agfv"},"agf");